version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: app-proposta
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5


  backend-proposta-app:
    build:
      context: ./app-proposta/.
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      ACTIVE_PROFILE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/app-proposta?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      DEFAULT_SCHEMA: apiproposta
      SPRING_RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_LISTENER_SIMPLE_RETRY_ENABLED: true
      RABBITMQ_LISTENER_SIMPLE_RETRY_MAX_ATTEMPTS: 3
      propostapendent_exchange: proposta-pendente.ex
      propostapendentdlq_exchange: proposta-pendente-dlq.ex
      propostaconcluida_exchange: proposta-concluida.ex
      propostaconcluidadlq_exchange: proposta-concluida-dlq.ex
    # command:
    #   sh sleep 10


  backend-notificacao-app:
    build:
      context: ./notificacao/.
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      ACTIVE_PROFILE: dev
      SPRING_RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_LISTENER_SIMPLE_RETRY_ENABLED: true
      RABBITMQ_LISTENER_SIMPLE_RETRY_MAX_ATTEMPTS: 3
      propostapendent_exchange: proposta-pendente.ex
      propostaconcluida_exchange: proposta-concluida.ex
      queue_proposta_pendente: proposta-pendente.ms-notificacao
      queue_proposta_concluida: proposta-concluida.ms-notificacao



  backend-analise-credito-app:
    build:
      context: ./app-analisecredito/.
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      ACTIVE_PROFILE: dev
      SPRING_RABBITMQ_HOST: rabbitmq
#      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_LISTENER_SIMPLE_RETRY_ENABLED: true
      RABBITMQ_LISTENER_SIMPLE_RETRY_MAX_ATTEMPTS: 3
      propostapendent_exchange: proposta-pendente.ex
      propostaconcluida_exchange: proposta-concluida.ex
      queue_proposta_pendente: proposta-pendente.ms-analise-credito
      queue_proposta_concluida: proposta-concluida.ms-notificacao


#  frontend:
#    image: matheuspieropan/proposta-web
#    ports:
#      - "3000:80"
##    depends_on:
##      - backend

volumes:
  db-data: